#!/usr/bin/env python3
"""
Report formatting for company SWOT analysis.

This module provides the function to format SWOT analysis data
as a markdown report with enhanced data visualization.
"""

from datetime import datetime
from typing import Dict, Any


def format_swot_report(company_name: str, data_sources: Dict[str, Any],
                       swot_analysis: Dict[str, list], analysis_date: str) -> str:
    """Format SWOT as markdown report with enhanced data.

    Args:
        company_name: Name of the company being analyzed
        data_sources: Dictionary containing all collected data (clinical_pipeline,
                      financial_data, approved_products, ema_products, market_performance)
        swot_analysis: Dictionary with strengths, weaknesses, opportunities, threats lists
        analysis_date: Date string for the analysis (YYYY-MM-DD format)

    Returns:
        Formatted markdown report string
    """
    # Extract financial data for display
    financial = data_sources.get('financial_data', {})
    revenue_current = financial.get('revenue', {}).get('current') or financial.get('revenue_current') or 0
    rd_current = financial.get('rd_expense', {}).get('current') or financial.get('rd_spending') or 0

    # Extract lead drugs for summary
    lead_drugs = data_sources.get('clinical_pipeline', {}).get('lead_drugs', [])
    lead_drugs_str = ', '.join(d['name'] for d in lead_drugs[:3]) if lead_drugs else 'N/A'

    # Build data sources table
    pipeline = data_sources.get('clinical_pipeline', {})
    fda = data_sources.get('approved_products', {})
    ema = data_sources.get('ema_products', {})
    market = data_sources.get('market_performance', {})

    phase_summary = ', '.join(f"{k}: {v}" for k, v in list(pipeline.get('phase_distribution', {}).items())[:3])

    # Check for insufficient data flag
    insufficient_data = swot_analysis.get('_insufficient_data', False)

    report = f"""# {company_name} SWOT Analysis

**Analysis Date:** {analysis_date}
**Generated by:** Pharmaceutical Research Intelligence Platform

---
"""
    if insufficient_data:
        report += f"""
> **Note:** Insufficient data available for {company_name}. This company may not be a pharmaceutical/biotechnology company, or may not file with SEC/FDA/EMA. Results below should be interpreted with caution.

"""

    report += f"""## Executive Summary

Comprehensive SWOT analysis evaluating {company_name}'s strategic position across clinical development, commercial operations, and market performance.

**Lead Pipeline Assets:** {lead_drugs_str}

### Data Sources Summary

| Source | Count | Details |
|--------|-------|---------|
| Active Clinical Pipeline | {pipeline.get('total_trials', 0)} trials | {phase_summary} (recruiting/ongoing only) |
| Financial Data | SEC EDGAR | Revenue: ${revenue_current/1e9:.1f}B, R&D: ${rd_current/1e6:.0f}M |
| FDA Products | {fda.get('total_products', 0)} | Therapeutic areas: {len(fda.get('therapeutic_areas', {}))} |
| EMA Products | {ema.get('total_products', 0) if ema else 'N/A'} | EU-authorized medicines |
| Market Cap | ${(market.get('market_cap') or 0)/1e9:.1f}B | Yahoo Finance |

"""

    # Add lead drugs section if available
    if lead_drugs:
        # Check if any drug has a reason (approved drug with ongoing trials)
        has_reasons = any(drug.get('reason') for drug in lead_drugs[:5])

        if has_reasons:
            report += """### Lead Pipeline Drugs

| Drug | Indication | Active Trials | Highest Phase | Reason |
|------|------------|--------------|---------------|--------|
"""
        else:
            report += """### Lead Pipeline Drugs

| Drug | Indication | Active Trials | Highest Phase |
|------|------------|--------------|---------------|
"""
        for drug in lead_drugs[:5]:
            indication = drug.get('indication', 'N/A') or 'N/A'
            # Truncate long indications for table display
            if len(indication) > 35:
                indication = indication[:32] + '...'
            if has_reasons:
                reason = drug.get('reason') or '-'
                report += f"| {drug['name']} | {indication} | {drug['trial_count']} | {drug['highest_phase']} | {reason} |\n"
            else:
                report += f"| {drug['name']} | {indication} | {drug['trial_count']} | {drug['highest_phase']} |\n"

    # Add segment revenue breakdown if available
    segment_revenue = financial.get('segment_revenue', {})
    if segment_revenue:
        total_seg_rev = sum(segment_revenue.values())
        report += """\n### Revenue by Product/Segment (XBRL)

| Product | Revenue | % of Total |
|---------|---------|------------|
"""

        def extract_product_name(seg_name: str) -> str:
            """Extract clean product name from XBRL segment name.

            Examples:
            - "HIVProducts Biktarvy" -> "Biktarvy"
            - "Liver Disease Products Vemlidy" -> "Vemlidy"
            - "Trodelvy" -> "Trodelvy"
            """
            # Common category prefixes to strip
            words = seg_name.split()
            if len(words) >= 2:
                # The last word is usually the product name
                # Check if it looks like a product (capitalized, 4+ chars)
                last_word = words[-1]
                if len(last_word) >= 4 and last_word[0].isupper():
                    return last_word
            return seg_name

        for seg_name, seg_value in list(segment_revenue.items())[:6]:
            display_name = extract_product_name(seg_name)
            pct = (seg_value / total_seg_rev * 100) if total_seg_rev > 0 else 0
            if seg_value >= 1e9:
                report += f"| {display_name} | ${seg_value/1e9:.2f}B | {pct:.0f}% |\n"
            elif seg_value >= 1e6:
                report += f"| {display_name} | ${seg_value/1e6:.0f}M | {pct:.0f}% |\n"
            else:
                report += f"| {display_name} | ${seg_value/1e3:.0f}K | {pct:.0f}% |\n"

    # Add geographic revenue breakdown if available
    geographic_revenue = financial.get('geographic_revenue', {})
    if geographic_revenue:
        report += """\n### Revenue by Geography (XBRL)

| Region | Revenue |
|--------|---------|
"""
        for geo_name, geo_value in list(geographic_revenue.items())[:5]:
            if geo_value >= 1e9:
                report += f"| {geo_name} | ${geo_value/1e9:.2f}B |\n"
            elif geo_value >= 1e6:
                report += f"| {geo_name} | ${geo_value/1e6:.0f}M |\n"
            else:
                report += f"| {geo_name} | ${geo_value/1e3:.0f}K |\n"

    # Add Patent/LOE section if available
    patent_data = fda.get('patent_data', {})
    products_with_patents = patent_data.get('products_with_patents', {})
    if products_with_patents:
        report += """\n### Patent Expiry Timeline (Orange Book)

| Product | Earliest Expiry | Latest Expiry | Patents |
|---------|----------------|---------------|---------|
"""
        for prod_name, prod_info in list(products_with_patents.items())[:8]:
            earliest = prod_info.get('earliest_expiry', 'N/A')
            latest = prod_info.get('latest_expiry', 'N/A')
            patent_count = prod_info.get('patent_count', 0)
            ped_flag = " (PED)" if prod_info.get('has_pediatric_extension') else ""
            # Format dates more readably
            try:
                earliest_fmt = datetime.strptime(earliest, '%Y-%m-%d').strftime('%b %Y')
                latest_fmt = datetime.strptime(latest, '%Y-%m-%d').strftime('%b %Y')
            except:
                earliest_fmt = earliest
                latest_fmt = latest
            report += f"| {prod_name} | {earliest_fmt} | {latest_fmt} | {patent_count}{ped_flag} |\n"

        # Add note about biologics if we checked many products but found few
        checked = patent_data.get('total_products_checked', 0)
        found = patent_data.get('products_with_data', 0)
        if checked > 5 and found < checked / 2:
            report += f"\n*Note: {checked - found} products may be biologics (BLA) without Orange Book patent data.*\n"

    report += """
---

## **Strengths**

"""

    for item in swot_analysis['strengths']:
        report += f"\n**{item['category']}**\n"
        report += f"- {item['point']}\n"
        report += f"  - *Evidence:* {item['evidence']}\n"

    report += "\n---\n\n## **Weaknesses**\n"

    for item in swot_analysis['weaknesses']:
        report += f"\n**{item['category']}**\n"
        report += f"- {item['point']}\n"
        report += f"  - *Evidence:* {item['evidence']}\n"

    report += "\n---\n\n## **Opportunities**\n"

    for item in swot_analysis['opportunities']:
        report += f"\n**{item['category']}**\n"
        report += f"- {item['point']}\n"
        report += f"  - *Evidence:* {item['evidence']}\n"

    report += "\n---\n\n## **Threats**\n"

    for item in swot_analysis['threats']:
        report += f"\n**{item['category']}**\n"
        report += f"- {item['point']}\n"
        report += f"  - *Evidence:* {item['evidence']}\n"

    report += """

---

## **Sources**

- ClinicalTrials.gov - Clinical trial registry (active trials)
- SEC EDGAR - Financial filings (10-K reports, multi-year data)
- FDA Drugs Database - US approved products
- FDA Orange Book - Patent and exclusivity data (small molecules)
- EMA - European Medicines Agency (EU approved products)
- Yahoo Finance - Market performance

---

*This analysis is based on publicly available data for informational purposes only.*
"""

    return report
